// Vendors whose public status feed answers a plain request with no key.
// Every statuspage host was verified on 2026-10-01 to serve /api/v2/summary.json
// (Atlassian Statuspage, or a provider exposing the same API). Slack, Google
// Cloud and AWS run their own feeds and have their own adapters in main.js.
// Vendors that failed that check (HTML-only pages, 403s, private feeds) are
// left out rather than scraped: buyers can add any Statuspage URL themselves.

export const VENDORS = [
    { key: 'github', name: 'GitHub', category: 'devtools', kind: 'statuspage', host: 'www.githubstatus.com' },
    { key: 'openai', name: 'OpenAI', category: 'ai', kind: 'statuspage', host: 'status.openai.com' },
    { key: 'anthropic', name: 'Anthropic', category: 'ai', kind: 'statuspage', host: 'status.anthropic.com' },
    { key: 'atlassian', name: 'Atlassian', category: 'collaboration', kind: 'statuspage', host: 'status.atlassian.com' },
    { key: 'jira', name: 'Jira', category: 'devtools', kind: 'statuspage', host: 'jira-software.status.atlassian.com' },
    { key: 'confluence', name: 'Confluence', category: 'devtools', kind: 'statuspage', host: 'confluence.status.atlassian.com' },
    { key: 'bitbucket', name: 'Bitbucket', category: 'devtools', kind: 'statuspage', host: 'bitbucket.status.atlassian.com' },
    { key: 'trello', name: 'Trello', category: 'collaboration', kind: 'statuspage', host: 'trello.status.atlassian.com' },
    { key: 'cloudflare', name: 'Cloudflare', category: 'cloud', kind: 'statuspage', host: 'www.cloudflarestatus.com' },
    { key: 'shopify', name: 'Shopify', category: 'commerce', kind: 'statuspage', host: 'www.shopifystatus.com' },
    { key: 'twilio', name: 'Twilio', category: 'marketing-sales', kind: 'statuspage', host: 'status.twilio.com' },
    { key: 'zoom', name: 'Zoom', category: 'collaboration', kind: 'statuspage', host: 'status.zoom.us' },
    { key: 'dropbox', name: 'Dropbox', category: 'collaboration', kind: 'statuspage', host: 'status.dropbox.com' },
    { key: 'discord', name: 'Discord', category: 'collaboration', kind: 'statuspage', host: 'discordstatus.com' },
    { key: 'reddit', name: 'Reddit', category: 'collaboration', kind: 'statuspage', host: 'www.redditstatus.com' },
    { key: 'vercel', name: 'Vercel', category: 'cloud', kind: 'statuspage', host: 'www.vercel-status.com' },
    { key: 'netlify', name: 'Netlify', category: 'cloud', kind: 'statuspage', host: 'www.netlifystatus.com' },
    { key: 'digitalocean', name: 'DigitalOcean', category: 'cloud', kind: 'statuspage', host: 'status.digitalocean.com' },
    { key: 'linode', name: 'Linode', category: 'cloud', kind: 'statuspage', host: 'status.linode.com' },
    { key: 'datadog', name: 'Datadog', category: 'observability', kind: 'statuspage', host: 'status.datadoghq.com' },
    { key: 'new-relic', name: 'New Relic', category: 'observability', kind: 'statuspage', host: 'status.newrelic.com' },
    { key: 'sentry', name: 'Sentry', category: 'devtools', kind: 'statuspage', host: 'status.sentry.io' },
    { key: 'notion', name: 'Notion', category: 'collaboration', kind: 'statuspage', host: 'www.notion-status.com' },
    { key: 'figma', name: 'Figma', category: 'collaboration', kind: 'statuspage', host: 'status.figma.com' },
    { key: 'asana', name: 'Asana', category: 'collaboration', kind: 'statuspage', host: 'status.asana.com' },
    { key: 'airtable', name: 'Airtable', category: 'collaboration', kind: 'statuspage', host: 'status.airtable.com' },
    { key: 'hubspot', name: 'HubSpot', category: 'marketing-sales', kind: 'statuspage', host: 'status.hubspot.com' },
    { key: 'mailgun', name: 'Mailgun', category: 'marketing-sales', kind: 'statuspage', host: 'status.mailgun.com' },
    { key: 'segment', name: 'Segment', category: 'marketing-sales', kind: 'statuspage', host: 'status.segment.com' },
    { key: 'mixpanel', name: 'Mixpanel', category: 'marketing-sales', kind: 'statuspage', host: 'status.mixpanel.com' },
    { key: 'amplitude', name: 'Amplitude', category: 'marketing-sales', kind: 'statuspage', host: 'status.amplitude.com' },
    { key: 'npm', name: 'npm', category: 'devtools', kind: 'statuspage', host: 'status.npmjs.org' },
    { key: 'docker', name: 'Docker', category: 'devtools', kind: 'statuspage', host: 'www.dockerstatus.com' },
    { key: 'circleci', name: 'CircleCI', category: 'devtools', kind: 'statuspage', host: 'status.circleci.com' },
    { key: 'supabase', name: 'Supabase', category: 'cloud', kind: 'statuspage', host: 'status.supabase.com' },
    { key: 'contentful', name: 'Contentful', category: 'marketing-sales', kind: 'statuspage', host: 'www.contentfulstatus.com' },
    { key: 'squarespace', name: 'Squarespace', category: 'marketing-sales', kind: 'statuspage', host: 'status.squarespace.com' },
    { key: 'webflow', name: 'Webflow', category: 'marketing-sales', kind: 'statuspage', host: 'status.webflow.com' },
    { key: 'zapier', name: 'Zapier', category: 'marketing-sales', kind: 'statuspage', host: 'status.zapier.com' },
    { key: 'box', name: 'Box', category: 'collaboration', kind: 'statuspage', host: 'status.box.com' },
    { key: 'miro', name: 'Miro', category: 'collaboration', kind: 'statuspage', host: 'status.miro.com' },
    { key: 'linear', name: 'Linear', category: 'devtools', kind: 'statuspage', host: 'linearstatus.com' },
    { key: 'postman', name: 'Postman', category: 'devtools', kind: 'statuspage', host: 'status.postman.com' },
    { key: 'cursor', name: 'Cursor', category: 'ai', kind: 'statuspage', host: 'status.cursor.com' },
    { key: 'cohere', name: 'Cohere', category: 'ai', kind: 'statuspage', host: 'status.cohere.com' },
    { key: 'groq', name: 'Groq', category: 'ai', kind: 'statuspage', host: 'groqstatus.com' },
    { key: 'perplexity', name: 'Perplexity', category: 'ai', kind: 'statuspage', host: 'status.perplexity.com' },
    { key: 'elevenlabs', name: 'ElevenLabs', category: 'ai', kind: 'statuspage', host: 'status.elevenlabs.io' },
    { key: 'pinecone', name: 'Pinecone', category: 'ai', kind: 'statuspage', host: 'status.pinecone.io' },
    { key: 'snowflake', name: 'Snowflake', category: 'cloud', kind: 'statuspage', host: 'status.snowflake.com' },
    { key: 'confluent', name: 'Confluent', category: 'cloud', kind: 'statuspage', host: 'status.confluent.cloud' },
    { key: 'elastic', name: 'Elastic', category: 'cloud', kind: 'statuspage', host: 'status.elastic.co' },
    { key: 'grafana', name: 'Grafana', category: 'observability', kind: 'statuspage', host: 'status.grafana.com' },
    { key: 'honeycomb', name: 'Honeycomb', category: 'observability', kind: 'statuspage', host: 'status.honeycomb.io' },
    { key: 'launchdarkly', name: 'LaunchDarkly', category: 'devtools', kind: 'statuspage', host: 'status.launchdarkly.com' },
    { key: 'square', name: 'Square', category: 'payments-finance', kind: 'statuspage', host: 'www.issquareup.com' },
    { key: 'plaid', name: 'Plaid', category: 'payments-finance', kind: 'statuspage', host: 'status.plaid.com' },
    { key: 'coinbase', name: 'Coinbase', category: 'payments-finance', kind: 'statuspage', host: 'status.coinbase.com' },
    { key: 'kraken', name: 'Kraken', category: 'payments-finance', kind: 'statuspage', host: 'status.kraken.com' },
    { key: 'gemini', name: 'Gemini', category: 'payments-finance', kind: 'statuspage', host: 'status.gemini.com' },
    { key: 'robinhood', name: 'Robinhood', category: 'payments-finance', kind: 'statuspage', host: 'status.robinhood.com' },
    { key: 'cloudinary', name: 'Cloudinary', category: 'cloud', kind: 'statuspage', host: 'status.cloudinary.com' },
    { key: 'imgix', name: 'Imgix', category: 'cloud', kind: 'statuspage', host: 'status.imgix.com' },
    { key: 'mux', name: 'Mux', category: 'cloud', kind: 'statuspage', host: 'status.mux.com' },
    { key: 'vimeo', name: 'Vimeo', category: 'collaboration', kind: 'statuspage', host: 'www.vimeostatus.com' },
    { key: 'canva', name: 'Canva', category: 'collaboration', kind: 'statuspage', host: 'www.canvastatus.com' },
    { key: 'monday-com', name: 'monday.com', category: 'collaboration', kind: 'statuspage', host: 'status.monday.com' },
    { key: 'clickup', name: 'ClickUp', category: 'collaboration', kind: 'statuspage', host: 'clickup.statuspage.io' },
    { key: 'smartsheet', name: 'Smartsheet', category: 'collaboration', kind: 'statuspage', host: 'status.smartsheet.com' },
    { key: 'help-scout', name: 'Help Scout', category: 'support', kind: 'statuspage', host: 'status.helpscout.net' },
    { key: 'gorgias', name: 'Gorgias', category: 'support', kind: 'statuspage', host: 'status.gorgias.com' },
    { key: 'klaviyo', name: 'Klaviyo', category: 'marketing-sales', kind: 'statuspage', host: 'status.klaviyo.com' },
    { key: 'brevo', name: 'Brevo', category: 'marketing-sales', kind: 'statuspage', host: 'status.brevo.com' },
    { key: 'activecampaign', name: 'ActiveCampaign', category: 'marketing-sales', kind: 'statuspage', host: 'status.activecampaign.com' },
    { key: 'typeform', name: 'Typeform', category: 'marketing-sales', kind: 'statuspage', host: 'status.typeform.com' },
    { key: 'hotjar', name: 'Hotjar', category: 'marketing-sales', kind: 'statuspage', host: 'status.hotjar.com' },
    { key: 'aircall', name: 'Aircall', category: 'marketing-sales', kind: 'statuspage', host: 'status.aircall.io' },
    { key: 'gusto', name: 'Gusto', category: 'hr', kind: 'statuspage', host: 'status.gusto.com' },
    { key: 'rippling', name: 'Rippling', category: 'hr', kind: 'statuspage', host: 'status.rippling.com' },
    { key: 'greenhouse', name: 'Greenhouse', category: 'hr', kind: 'statuspage', host: 'status.greenhouse.io' },
    { key: 'lever', name: 'Lever', category: 'hr', kind: 'statuspage', host: 'status.lever.co' },
    { key: 'xero', name: 'Xero', category: 'payments-finance', kind: 'statuspage', host: 'status.xero.com' },
    { key: 'brex', name: 'Brex', category: 'payments-finance', kind: 'statuspage', host: 'status.brex.com' },
    { key: '1password', name: '1Password', category: 'security-identity', kind: 'statuspage', host: 'status.1password.com' },
    { key: 'duo', name: 'Duo', category: 'security-identity', kind: 'statuspage', host: 'status.duo.com' },
    { key: 'render', name: 'Render', category: 'cloud', kind: 'statuspage', host: 'status.render.com' },
    { key: 'fly-io', name: 'Fly.io', category: 'cloud', kind: 'statuspage', host: 'status.flyio.net' },
    { key: 'wasabi', name: 'Wasabi', category: 'cloud', kind: 'statuspage', host: 'status.wasabi.com' },
    { key: 'epic-games', name: 'Epic Games', category: 'collaboration', kind: 'statuspage', host: 'status.epicgames.com' },
    { key: 'statuspage', name: 'Statuspage', category: 'devtools', kind: 'statuspage', host: 'metastatus.statuspage.io' },
    { key: 'tailscale', name: 'Tailscale', category: 'cloud', kind: 'statuspage', host: 'status.tailscale.com' },
    { key: 'jumpcloud', name: 'JumpCloud', category: 'security-identity', kind: 'statuspage', host: 'status.jumpcloud.com' },
    { key: 'clerk', name: 'Clerk', category: 'security-identity', kind: 'statuspage', host: 'status.clerk.com' },
    { key: 'resend', name: 'Resend', category: 'marketing-sales', kind: 'statuspage', host: 'resend-status.com' },
    { key: 'planetscale', name: 'PlanetScale', category: 'cloud', kind: 'statuspage', host: 'www.planetscalestatus.com' },
    { key: 'upstash', name: 'Upstash', category: 'cloud', kind: 'statuspage', host: 'status.upstash.com' },
    { key: 'bunny', name: 'Bunny', category: 'cloud', kind: 'statuspage', host: 'status.bunny.net' },
    { key: 'buffer', name: 'Buffer', category: 'marketing-sales', kind: 'statuspage', host: 'status.buffer.com' },
    { key: 'hootsuite', name: 'Hootsuite', category: 'marketing-sales', kind: 'statuspage', host: 'status.hootsuite.com' },
    { key: 'apify', name: 'Apify', category: 'devtools', kind: 'statuspage', host: 'status.apify.com' },
    { key: 'twitch', name: 'Twitch', category: 'collaboration', kind: 'statuspage', host: 'status.twitch.com' },
    { key: 'snyk', name: 'Snyk', category: 'devtools', kind: 'statuspage', host: 'status.snyk.io' },
    { key: 'travis-ci', name: 'Travis CI', category: 'devtools', kind: 'statuspage', host: 'www.traviscistatus.com' },
    { key: 'buildkite', name: 'Buildkite', category: 'devtools', kind: 'statuspage', host: 'www.buildkitestatus.com' },
    { key: 'netdata', name: 'Netdata', category: 'cloud', kind: 'statuspage', host: 'status.netdata.cloud' },
    { key: 'grammarly', name: 'Grammarly', category: 'collaboration', kind: 'statuspage', host: 'status.grammarly.com' },
    { key: 'dropbox-sign', name: 'Dropbox Sign', category: 'collaboration', kind: 'statuspage', host: 'status.hellosign.com' },
    { key: 'close', name: 'Close', category: 'marketing-sales', kind: 'statuspage', host: 'status.close.com' },
    { key: 'gong', name: 'Gong', category: 'marketing-sales', kind: 'statuspage', host: 'status.gong.io' },
    { key: 'zoominfo', name: 'ZoomInfo', category: 'marketing-sales', kind: 'statuspage', host: 'status.zoominfo.com' },
    { key: 'mapbox', name: 'Mapbox', category: 'cloud', kind: 'statuspage', host: 'status.mapbox.com' },
    { key: 'bandwidth', name: 'Bandwidth', category: 'marketing-sales', kind: 'statuspage', host: 'status.bandwidth.com' },
    { key: 'fireworks-ai', name: 'Fireworks AI', category: 'ai', kind: 'statuspage', host: 'status.fireworks.ai' },
    { key: 'runway', name: 'Runway', category: 'ai', kind: 'statuspage', host: 'status.runwayml.com' },
    { key: 'hex', name: 'Hex', category: 'devtools', kind: 'statuspage', host: 'status.hex.tech' },
    { key: 'dbt-cloud', name: 'dbt Cloud', category: 'cloud', kind: 'statuspage', host: 'status.getdbt.com' },
    { key: 'metabase', name: 'Metabase', category: 'cloud', kind: 'statuspage', host: 'status.metabase.com' },
    { key: 'retool', name: 'Retool', category: 'devtools', kind: 'statuspage', host: 'status.retool.com' },
    { key: 'bubble', name: 'Bubble', category: 'devtools', kind: 'statuspage', host: 'status.bubble.io' },
    { key: 'wix', name: 'Wix', category: 'commerce', kind: 'statuspage', host: 'status.wix.com' },
    { key: 'bigcommerce', name: 'BigCommerce', category: 'commerce', kind: 'statuspage', host: 'status.bigcommerce.com' },
    { key: 'recharge', name: 'Recharge', category: 'commerce', kind: 'statuspage', host: 'status.rechargepayments.com' },
    { key: 'chargebee', name: 'Chargebee', category: 'payments-finance', kind: 'statuspage', host: 'status.chargebee.com' },
    { key: 'paddle', name: 'Paddle', category: 'payments-finance', kind: 'statuspage', host: 'paddlestatus.com' },
    { key: 'recurly', name: 'Recurly', category: 'payments-finance', kind: 'statuspage', host: 'status.recurly.com' },
    { key: 'wise', name: 'Wise', category: 'payments-finance', kind: 'statuspage', host: 'status.wise.com' },
    { key: 'mercury', name: 'Mercury', category: 'payments-finance', kind: 'statuspage', host: 'status.mercury.com' },
    { key: 'klarna', name: 'Klarna', category: 'payments-finance', kind: 'statuspage', host: 'status.klarna.com' },
    { key: 'afterpay', name: 'Afterpay', category: 'payments-finance', kind: 'statuspage', host: 'status.afterpay.com' },
    { key: 'affirm', name: 'Affirm', category: 'payments-finance', kind: 'statuspage', host: 'status.affirm.com' },
    { key: 'marqeta', name: 'Marqeta', category: 'payments-finance', kind: 'statuspage', host: 'status.marqeta.com' },
    { key: 'slack', name: 'Slack', category: 'collaboration', kind: 'slack', host: 'slack-status.com' },
    { key: 'google-cloud', name: 'Google Cloud', category: 'cloud', kind: 'gcp', host: 'status.cloud.google.com' },
    { key: 'aws', name: 'AWS', category: 'cloud', kind: 'aws', host: 'health.aws.amazon.com' },
];

// What buyers type, mapped to a vendor key.
export const ALIASES = {
    sendgrid: 'twilio', 'twilio sendgrid': 'twilio', claude: 'anthropic', chatgpt: 'openai',
    'cloudflare workers': 'cloudflare', gcp: 'google-cloud', 'google cloud platform': 'google-cloud',
    'amazon web services': 'aws', jira: 'jira', 'jira software': 'jira', 'hellosign': 'dropbox-sign',
    datadoghq: 'datadog', 'fly': 'fly-io', 'monday': 'monday-com', 'dbt': 'dbt-cloud',
};
