// Curated universe of well-known tech / startup companies and their public,
// keyless ATS board tokens. Every token here was verified to resolve to a live
// job board (2026-07-14). This list changes slowly (companies rarely switch
// ATS); buyers can extend it via the extraCompanies input. Format: [provider,
// token, displayName].

export const COMPANIES = [
    // Greenhouse
    ['greenhouse', 'stripe', 'Stripe'],
    ['greenhouse', 'airbnb', 'Airbnb'],
    ['greenhouse', 'coinbase', 'Coinbase'],
    ['greenhouse', 'databricks', 'Databricks'],
    ['greenhouse', 'robinhood', 'Robinhood'],
    ['greenhouse', 'instacart', 'Instacart'],
    ['greenhouse', 'dropbox', 'Dropbox'],
    ['greenhouse', 'pinterest', 'Pinterest'],
    ['greenhouse', 'lyft', 'Lyft'],
    ['greenhouse', 'gitlab', 'GitLab'],
    ['greenhouse', 'reddit', 'Reddit'],
    ['greenhouse', 'discord', 'Discord'],
    ['greenhouse', 'figma', 'Figma'],
    ['greenhouse', 'asana', 'Asana'],
    ['greenhouse', 'twitch', 'Twitch'],
    ['greenhouse', 'cloudflare', 'Cloudflare'],
    ['greenhouse', 'affirm', 'Affirm'],
    ['greenhouse', 'brex', 'Brex'],
    ['greenhouse', 'scaleai', 'Scale AI'],
    ['greenhouse', 'samsara', 'Samsara'],
    ['greenhouse', 'flexport', 'Flexport'],
    ['greenhouse', 'sofi', 'SoFi'],
    ['greenhouse', 'chime', 'Chime'],
    ['greenhouse', 'carta', 'Carta'],
    ['greenhouse', 'gusto', 'Gusto'],
    ['greenhouse', 'airtable', 'Airtable'],
    ['greenhouse', 'vercel', 'Vercel'],
    ['greenhouse', 'mixpanel', 'Mixpanel'],
    ['greenhouse', 'amplitude', 'Amplitude'],
    ['greenhouse', 'elastic', 'Elastic'],
    ['greenhouse', 'mongodb', 'MongoDB'],
    ['greenhouse', 'datadog', 'Datadog'],
    ['greenhouse', 'okta', 'Okta'],
    ['greenhouse', 'twilio', 'Twilio'],
    ['greenhouse', 'roblox', 'Roblox'],
    // Lever
    ['lever', 'spotify', 'Spotify'],
    ['lever', 'palantir', 'Palantir'],
    ['lever', 'veeva', 'Veeva'],
    // Ashby
    ['ashby', 'ramp', 'Ramp'],
    ['ashby', 'openai', 'OpenAI'],
    ['ashby', 'notion', 'Notion'],
    ['ashby', 'linear', 'Linear'],
    ['ashby', 'runway', 'Runway'],
    ['ashby', 'clipboard', 'Clipboard Health'],
    ['ashby', 'posthog', 'PostHog'],
    ['ashby', 'modal', 'Modal'],
    ['ashby', 'replit', 'Replit'],
    ['ashby', 'vanta', 'Vanta'],
    ['ashby', 'watershed', 'Watershed'],
];
